#!/usr/bin/env node
/**
 * agent-memory Anvil adapter installer
 *
 * - Verifies local agent-memory prerequisites for Anvil usage
 * - Ensures helper scripts are executable
 * - Writes a local Anvil env template at .anvil/agent-memory.env
 * - Prints usage for wrapper + hint toggles
 */

const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.resolve(__dirname);
const PLATFORM = os.platform();
const PYTHON = path.join(ROOT, '.venv', PLATFORM === 'win32' ? 'Scripts' : 'bin', 'python');
const MCP_SERVER = path.join(ROOT, 'mcp_server.py');
const ANVIL_DIR = path.join(ROOT, '.anvil');
const ANVIL_ENV = path.join(ANVIL_DIR, 'agent-memory.env');

const REQUIRED = [
  'integrations/anvil/README.md',
  'scripts/anvil-agent-memory.sh',
  'scripts/hints-config.js',
];

function exists(rel) {
  return fs.existsSync(path.join(ROOT, rel));
}

function ensureExecutableBits() {
  if (PLATFORM === 'win32') return;
  for (const rel of ['scripts/anvil-agent-memory.sh', 'scripts/hints-config.js']) {
    const fp = path.join(ROOT, rel);
    try {
      fs.chmodSync(fp, 0o755);
    } catch {}
  }
}

function checkFiles() {
  const missing = REQUIRED.filter((f) => !exists(f));
  if (missing.length) {
    console.error('Missing Anvil adapter files:');
    for (const f of missing) console.error(`- ${f}`);
    process.exit(1);
  }
  if (!fs.existsSync(PYTHON)) {
    console.error(`Python venv not found at ${PYTHON}`);
    console.error('Run `node install.js` first (or create .venv manually).');
    process.exit(1);
  }
  if (!fs.existsSync(MCP_SERVER)) {
    console.error(`MCP server file not found: ${MCP_SERVER}`);
    process.exit(1);
  }
}

function writeAnvilEnvTemplate() {
  fs.mkdirSync(ANVIL_DIR, { recursive: true });
  if (fs.existsSync(ANVIL_ENV)) return;
  const body = [
    '# agent-memory Anvil integration env',
    '# Generated by install-anvil.js',
    'AGENT_MEMORY_SERVER=http://localhost:3377',
    'AGENT_MEMORY_HINTS_ENABLED=1',
    'AGENT_MEMORY_SESSION_HINTS_ENABLED=1',
    'AGENT_MEMORY_PRE_TOOL_HINTS_ENABLED=1',
    '',
  ].join('\n');
  fs.writeFileSync(ANVIL_ENV, body, 'utf8');
}

function printSummary() {
  console.log('\nagent-memory Anvil adapter installed');
  console.log('');
  console.log(`Wrapper: ${path.join(ROOT, 'scripts', 'anvil-agent-memory.sh')}`);
  console.log(`Env template: ${ANVIL_ENV}`);
  console.log(`Hint toggles: ${path.join(ROOT, 'scripts', 'hints-config.js')}`);
  console.log(`Docs: ${path.join(ROOT, 'integrations', 'anvil', 'README.md')}`);
  console.log('');
  console.log('Usage:');
  console.log('  ./scripts/install-agent-memory-anvil.sh');
  console.log('  ./scripts/anvil-agent-memory.sh <anvil-command> [args...]');
  console.log('  node scripts/hints-config.js set session on');
  console.log('  node scripts/hints-config.js set pretool off');
}

function main() {
  checkFiles();
  ensureExecutableBits();
  writeAnvilEnvTemplate();
  printSummary();
}

main();
